FROM nginx
ADD index.html  /usr/share/nginx/html/index.html
COPY js /usr/share/nginx/html/js
COPY images /usr/share/nginx/html/images
COPY fonts /usr/share/nginx/html/fonts
COPY css /usr/share/nginx/html/css

EXPOSE 80
